# Generated by Django 5.0.1 on 2025-07-20 09:35

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du client"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("general_contractor", "Entreprise générale"),
                            ("specialty_contractor", "Entreprise spécialisée"),
                            ("architect", "Architecte"),
                            ("engineer", "Bureau d'études"),
                            ("developer", "Promoteur"),
                            ("other", "Autre"),
                        ],
                        default="general_contractor",
                        max_length=50,
                        verbose_name="Type d'entreprise",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email de contact",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Adresse"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Nombre max d'utilisateurs"
                    ),
                ),
                (
                    "storage_limit_gb",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Limite stockage (GB)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Client (Tenant)",
                "verbose_name_plural": "Clients (Tenants)",
                "indexes": [
                    models.Index(fields=["name"], name="tenant_sche_name_d54e3c_idx"),
                    models.Index(
                        fields=["is_active"], name="tenant_sche_is_acti_1ad569_idx"
                    ),
                    models.Index(
                        fields=["company_type"], name="tenant_sche_company_d042af_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="tenant_sche_created_5e8891_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Description du domaine",
                    ),
                ),
                (
                    "is_https_only",
                    models.BooleanField(default=True, verbose_name="HTTPS uniquement"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenant_schema.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domaine",
                "verbose_name_plural": "Domaines",
                "indexes": [
                    models.Index(
                        fields=["domain"], name="tenant_sche_domain_8f3259_idx"
                    ),
                    models.Index(
                        fields=["tenant"], name="tenant_sche_tenant__dcfcf3_idx"
                    ),
                    models.Index(
                        fields=["is_primary"], name="tenant_sche_is_prim_21027f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="tenant_sche_created_da96f4_idx"
                    ),
                ],
            },
        ),
    ]
