# Generated by Django 5.2 on 2025-07-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_schema", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="tenant_uuid",
            field=models.UUIDField(
                blank=True, help_text="UUID original du tenant", null=True, unique=True
            ),
        ),
    ]
