# Generated by Django 5.0.1 on 2025-07-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_schema", "0002_client_tenant_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="tenant_sche_name_d54e3c_idx",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="tenant_sche_company_d042af_idx",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="tenant_sche_created_5e8891_idx",
        ),
        migrations.RemoveIndex(
            model_name="domain",
            name="tenant_sche_domain_8f3259_idx",
        ),
        migrations.RemoveIndex(
            model_name="domain",
            name="tenant_sche_tenant__dcfcf3_idx",
        ),
        migrations.RemoveIndex(
            model_name="domain",
            name="tenant_sche_is_prim_21027f_idx",
        ),
        migrations.RemoveIndex(
            model_name="domain",
            name="tenant_sche_created_da96f4_idx",
        ),
        migrations.RemoveField(
            model_name="client",
            name="address",
        ),
        migrations.RemoveField(
            model_name="client",
            name="company_type",
        ),
        migrations.RemoveField(
            model_name="client",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="client",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="client",
            name="description",
        ),
        migrations.RemoveField(
            model_name="client",
            name="max_users",
        ),
        migrations.RemoveField(
            model_name="client",
            name="storage_limit_gb",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="description",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="is_https_only",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="client",
            name="max_library_items",
            field=models.IntegerField(
                default=10000, verbose_name="Nombre maximum d'éléments de bibliothèque"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="tenant_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="UUID fourni par le service tenant",
                null=True,
                unique=True,
                verbose_name="UUID du tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["tenant_uuid"], name="tenant_sche_tenant__4c846e_idx"
            ),
        ),
    ]
